.ds VE LPRng-3.6.12
.TH LPR 1 \*(VE "LPRng"
.ig
Thu Jul 20 07:19:29 PDT 1995 Patrick Powell
..
.SH NAME
lpr \- off line print
.SH SYNOPSIS
.B lpr
[
.B \-A
]
[
.B \-b,l
]
[
.BI \-C " class"
]
[
.BI \-D " debugopt"
]
.ti +5n
[
.BI \-F " filterformat"
]
[
.B \-h
]
[
.BI \-i " indentcols"
]
.ti +5n
[
.B \-k
]
[
.BI \-J " job"
]
[
.BI \-K,# " copies"
]
.ti +5n
[
.BI \-m " mailTo"
]
[
.BI \-P " printer"
]
[
.B \-Q
]
[
.B \-r
]
.ti +5n
[
.BI \-R " remoteAccount"
]
[
.B \-s
]
[
.BI \-T " title"
]
[
.BI \-U " user"
]
.ti +5n
[
.B \-V
]
[
.BI \-w " width"
]
[
.BI \-Z " zoptions"
]
[
.BI \-1,2,3,4 " font"
]
.ti +5n
[
.IR filename " \|.\|.\|."
]
.SH DESCRIPTION
.B Lpr
uses a spooling daemon to print the named files when facilities
become available.  If no names appear, the standard input is assumed.
.SH OPTIONS
.TP 5
.B \-A
Use the authenticated transfer facilities if they are available.
.TP 5
.BI \-C " class"
Specify the job classification for use on the burst page and to
set the priority.
Priorities range from A (lowest) to Z (highest);
the default priority is A.
For example,
.br
.ti +0.5i
lpr \-C B foo.c
.br
sets the priority/class to B and the file foo.c is printed.
.TP 5
\fB\-D\fP\ \fIdebugoptions\fP
Debugging is controlled using the
.B \-D
option. This accepts a comma-separated list of debugging
settings. These settings take one of two forms: 
.BI facility =value, 
or
.B value 
to set an overall default value.
.TP 5
\fB\-F\fI filterformat\fR
Filter or format specification.
By default,
input is assumed to a standard text file and the
.I f
format is used;
the output device is assmed to be a simple line printer.
Therer are other formats available,
listed below.
Not all formats may be available on all printers;
see
.BR printcap (5)
for details.
Formats are single lower case letters;
the following are the valid arguments for
.B \-F
together with the assumed type of data.
For compatibility with previous versions of
.BR lpr ,
the format types can be used as options themselves
(i.e. by omitting the
.BR F )
except where noted below,
a warning may be issued in such cases.
.RS 5
.TP 5
.B "\-b, \-l"
either of these flags specifies a
binary or literal file,
and no processing is to be done.
Printed using the
.I f
format filter,
with processing suppressed.
.TP 5
.B \-c
data produced by
.BR cifplot (l).
.TP 5
.B \-d
output from
.BR tex (l)
(DVI format from Stanford).
.TP 5
.B \-g
standard plot data as produced by the
.BR plot (3X)
routines (see also
.BR plot (1G)
for the filters used by the printer spooler).
.TP 5
.B \-n
output from (device independent)
.BR troff .
.TP 5
.B \-p
First use
.BR pr (1)
to format the files,
then print using 
.I f
format.
.TP 5
.B \-r
The DREADED
.B "REMOVE AFTER PRINTING"
option.
Beware, for 
.I lpr
will delete the files after spooling them.
Present by demand from users for compatibility with other Berkeley lpr
implementation,
but really should NOT be present.
.TP 5
.B \-t
output from
.BR troff (1)
(originally cat phototypesetter commands,
but now we assume the same as the
.B n
format).
.TP 5
.B \-v
a raster image for devices like the Benson Varian.
.RE
.TP 5
\fB\-h\fP
No banner or header for this job.
.TP 5
.BI \-i " indentcols"
Indent input by indentcols.
Note that this option is not supported on all printers.
.TP 5
.BI -J " jobname"
Specify the job name to print on the burst page;
defaults to the name of the first file in job or
.I "(STDIN)"
if input is from a pipe.
.TP 5
.B \-k
When used as a filter,
.B lpr
normally creates a temporary file
for the input read from stdin before sending it to the remote
printer.
The
.B \-k
causes the job to be sent directly to the server.
If you kill the job in the middle of creation,
then the partly transferred file will get printed.
This option may not work with very large jobs or non-LPRng spoolers.
.TP 5
\fB\-K\fP\fIcopies\fP,\0\fB\-#\fP\fIcopies\fP
Specify the number of copies of each file to be printed.
.TP 5
.BI \-m " mailTo"
Send mail upon unsuccessful completion to user
.IR mailTo .
.TP 5
.BI \-P " printer"
Output to the specific printer;
the default is (in order of priority)
the explictly specified -P value,
the environment variable PRINTER,
the first entry in the printcap information,
and the default_printer entry from the
configuration file,
and finally the hard coded (site dependent) default_printer
value.
.TP 5
.B \-Q
Put the name of the spool queue into the job file.
This information can then be used by the spooling software
to control output format.
.TP 5
.BI \-R " remoteAccount"
Specify accounting information to be used by a remote system that prints
your output.
.sp
This parameter
can be used to specify a billing code to be charged for the
printing.
.TP 5
.B \-s
This flag is included for compatibility with other versions of
.BR lpr .
In these versions it will create a symbolic link to the files to be
printed.  
.B Lpr
now sends files directly to the server and it is irrelevant.
.TP 5
.BI \-T "  title"
Specify the title used by
.BR pr (1);
defaults to the file name.
.TP 5
\fB\-U\fP\ \fIusername\fP
The
.B \-U
option is used to specify a user name
for the job.
This is available only to ROOT or users listed in the
.I allow_user_setting
configuration option.
This is obviously a security loophole,
but it is present to allow systems such as SAMBA
to submit jobs on behalf of users.
See
.B "Authenticated Transfers"
below.
.TP 5
.B \-V
Verbose mode. Additional -V flags increase verbosity.
Use debug flags for extreme verbosity.
.TP 5
.BI \-w " width"
Specify the page width for printing the job.
.TP 5
.BI -Z " zoptions"
This option is used to pass options to the print spooler,
and is used when additional or specialized information
must be provided to the spooler.
.TP 5
.BI \-1,2,3,4 "fontname"
Specify a font to be mounted on font position \fIi\fR
for TROFF printing (Obsolete).
.SH FILENAMES
.PP
By default,
if no filenames are specified
.B lpr
will read stdin and print it.
.SH "AUTHENTICATED TRANSFERS"
.PP
The original LPR network protocol defined in RFC1179 did not
provide for user to server authentication.
This is now supported by LPRng.
See the LPRng support documentation for details on its operation
and support.
.SH COMPATIBILITY 
.PP
The LPRng version of
.B lpr
attempts to be functionaly compatible with common implementations of
.BR lpr .
However,
there are some commands and functionality that are deliberately missing.
.IP "\fB\-s\fP\ Symbolic Links" 5
(Berkeley LPR) This option specified that a symbolic link
to the original data file
rather than a copy of the data file was to be used when spooling jobs.
This opens up a variety of security problems,
as well as being ineffective when printing to a remote host.
.SH FILES
.PP
The files used by LPRng are set by values in the
printer configuration file.
The following are a commonly used set of default values.
.nf
.ta \w'/var/spool/lpd/printcap.<hostname>           'u
/etc/lpd.conf		LPRng configuration file
/etc/printcap		printer description file
/etc/lpd.perms	printer permissions
/var/spool/printer*		spool directories
/var/spool/printer*/printer	lock file for queue control
/var/spool/printer*/control.printer	queue control
/var/spool/printer*/active.printer	active job
/var/spool/printer*/log.printer	log file
.fi
.SH "SEE ALSO"
.BR lpd.conf (5),
.BR lpc (8),
.BR lpd (8),
.BR lpr (1),
.BR lpq (1),
.BR lprm (1),
.BR printcap (5),
.BR lpd.perms (5),
.BR pr (1).
.SH DIAGNOSTICS
.nf
Most of the diagnostics are self explanatory.
If you are puzzled over the exact cause of failure,
set the debugging level on (-D5) and run again.
The debugging information will 
help you to pinpoint the exact cause of failure.
.fi
.SH "HISTORY"
LPRng is a enhanced printer spooler system
with functionality similar to the Berkeley LPR software.
The LPRng mailing list is lprng@lprng.com;
subscribe by sending mail to lprng-request@lprng.com with
the word subscribe in the body.
The software is available from ftp://ftp.astart.com/pub/LPRng.
.SH "AUTHOR"
Patrick Powell <papowell@astart.com>.
