.ds VE LPRng-3.6.12
.TH LPRACCNT 1 \*(VE "LPRng"
.ig
lpraccnt.1,v 3.39 1998/03/29 18:37:49 papowell Exp
..
.SH NAME
lpraccnt \- receive accounting information
.SH SYNOPSIS
.B lpraccnt
[
.BI \-p port
] [
.BI \-D debuglevel
]
.SH DESCRIPTION
.PP
The
.B lpraccnt
program is a template for a printer accouting program.
It will open the specified TCP port,
and then wait for accounting or other information to be sent.
It prints this information on it standard output.
.SH OPTIONS
.IP "\fB\-p \fIport\fR" 5
wait for connections on this port (default 3000).
.IP "\fB\-D \fIdebuglevel\fR" 5
Set the debug level to the indicated value.
.SH "SEE ALSO"
.LP
lpd.conf(5),
lpc(8),
lpd(8),
lpr(1),
lpq(1),
lprm(1),
printcap(5),
lpd.conf(5),
pr(1).
.SH "HISTORY"
LPRng is a enhanced printer spooler system
with functionality similar to the Berkeley LPR software.
The LPRng mailing list is lprng@lprng.com;
subscribe by sending mail to lprng-request@lprng.com with
the word subscribe in the body.
The software is available from ftp://ftp.astart.com/pub/LPRng.
.SH "AUTHOR"
Patrick Powell <papowell@astart.com>.
