.TH "PLP_SNPRINTF" 3 "Dec 12, 1998" V98.12.13
.SH NAME
plp_snprintf, plp_vsnprintf - formatted output conversion
.SH SYNOPSIS
.br
#include <stdarg.h>
.br
void plp_snprintf(char *str, int size, const char *format, ...);
.br
void plp_vsnprintf(char *str, int size, const char *format, va_list ap);
.br
extern int visible_control;
.br
.SH "HISTORY"
LPRng is a enhanced printer spooler system
with functionality similar to the Berkeley LPR software.
The LPRng mailing list is lprng@lprng.com;
subscribe by sending mail to lprng-request@lprng.com with
the word subscribe in the body.
The software is available from ftp://ftp.astart.com/pub/LPRng.
.SH "AUTHOR"
Patrick Powell <papowell@astart.com>.
