.ds VE LPRng-3.5.1
.TH READFILECOUNT 1 \*(VE "LPRng"
.ig
readfilecount.1,v 3.40 1998/03/29 18:37:49 papowell Exp
..
.SH NAME
readfilecount \- read a specified number of bytes from input
.SH SYNOPSIS
.B readfilecount
.SH DESCRIPTION
.PP
The
.B readfilecount
program reads a single line from stdin (file descriptor 0).
This line should have the form below, where nnn is a decimal number.
.br
nnn\en
.LP
The following nnn bytes will then be read from stdin and
written to stdount.
.SH "SEE ALSO"
.LP
authenticate.pgp(1),
lpd(8),
lpd.conf(5),
pr(1).
.SH "HISTORY"
.LP
LPRng is a enhanced printer spooler system
with functionality similar to the Berkeley LPR software.
In 1988 Patrick Powell released
the PLP (Public Line Printer) software,
which went through several evolutions.
Justin Mason (jmason@iona.ie)
generated PLP4.0 from several older releases of PLP.
In 1992 Patrick Powell
release LPRng,
a completely redesigned and newly written version of the software.
.LP
The LPRng mailing list is plp@iona.ie;
subscribe by sending mail to plp-request@iona.ie with
the word subscribe in the body.
The software is available from ftp://iona.ie/pub/LPRng.
.LP
LPRng is distributed under the GNU software license for non-commercial
use,
the Artistic License for limited commercial use. 
Commerical support and licensing is available through
Patrick Powell <papowell@sdsu.edu>.
