#!/bin/sh
set -x
if [ -d /usr/share/man ] ; then
	mandir="--mandir=/usr/share/man"
fi
for i in /usr/kerberos /usr/local/kerberos /usr/local ; do
	if [ -d $i/include ] ; then CPPFLAGS="$CPPFLAGS -I$i/include"; fi
	if [ -d $i/lib ] ; then LDFLAGS="$LDFLAGS -L$i/lib"; fi
done

sh ./configure --prefix=/usr --sysconfdir=/etc $mandir --disable-shared \
 --disable-kerberos --enable-ssl --enable-force_localhost \
     LDFLAGS="$LDFLAGS" CPPFLAGS="$CPPFLAGS" \


# Here are some more flags you may want:
#
# LDFLAGS="$LDFLAGS -L/usr/local/lib" CPPFLAGS="$CPPFLAGS -I/usr/local/include" \
# --enable-nls --with-included-gettext \
# --enable-kerberos --enable-mit_kerberos4 \
# --disable-ssl --disable-tcpwrappers \
# --enable-nls --with-included-gettext \
#	--with-chooser_routine=test_chooser  --with-user_objs=user_objs.o  --with-user_include=user_objs.h
