###########################################################################
# LPRng - An Extended Print Spooler System
#
# Copyright 1988-1995 Patrick Powell, San Diego State University
#     papowell@sdsu.edu
# See LICENSE for conditions of use.
#
###########################################################################
# MODULE: UTILS/Makefile
# PURPOSE: generate utilities
# $Id: Makefile,v 1.1 1996/12/29 06:04:24 papowell Exp $
########################################################################## 

.PHONY: all clean ci install FRC realclean mostlyclean distclean

all:
realclean mostlyclean distclean clean:
install:
ci:
