#!/bin/sh
###########################################################################
# LPRng - An Extended Print Spooler System
#
# Copyright 1988-1995 Patrick Powell, San Diego State University
#     papowell@sdsu.edu
# See LICENSE for conditions of use.
#
###########################################################################
# MODULE: TESTSUPPORT/clearlog
# PURPOSE: clears the log files of test software
# $Id: clearlog,v 3.0 1996/05/19 04:06:42 papowell Exp $
########################################################################## 

echo >/tmp/LPD/t1/log
echo >/tmp/LPD/t2/log
echo >/tmp/LPD/t4/log
echo >/tmp/LPD/t5/log
