/* Automatically generated by po2tbl.sed from LPRng.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"No remote host specified", 2},
  {"Too many parameters\n", 3},
  {"fork failed - %s'", 4},
  {"Version %s\n", 5},
  {"\
usage: %s [-A] [-Ddebuglevel] [-Pprinter] [-V] [command]\n\
 with no commands, reads from stdin\n\
  -A           - use authentication\n\
  -Pprinter    - specify printer\n\
  -V           - increase information verbosity\n\
  -Ddebuglevel - debug level\n\
 commands:\n\
 abort   (printer[@host] | all)  - stop server\n\
 disable (printer[@host] | all)  - disable queueing\n\
 debug   (printer[@host] | all) debugparms - set debug level for printer\n\
 enable  (printer[@host] | all)  - enable  queueing\n\
 hold    (printer[@host] | all) (name[@host] | job | all)* - hold job\n\
 holdall (printer[@host] | all)  - hold all jobs on\n\
 kill    (printer[@host] | all)  - stop and restart server\n\
 lpd [HUP]  - get LPD PID, signal it to reread printcap and configuration\n\
 lpq (printer[@host] | all) (name[@host] | job | all)*     - invoke LPQ\n\
 lprm (printer[@host] | all) (name[@host]|host|job| all)*  - invoke LPRM\n\
 move printer (user|jobid)* target - move jobs to new queue\n\
 noholdall (printer[@host] | all)  - hold all jobs off\n\
 printcap (printer[@host] | all) - report printcap values\n\
 quit                            - exit LPC\n\
 redirect (printer[@host] | all) (printer@host | off )*    - redirect jobs\n\
 release  (printer[@host] | all) (name[@host] | job | all)* - release job\n\
 reread                          - LPD reread database information\n\
 start   (printer[@host] | all)  - start printing\n\
 status  (printer[@host] | all)  - status of printers\n\
 stop    (printer[@host] | all)  - stop  printing\n\
 topq    (printer[@host] | all) (name[@host] | job | all)* - reorder job\n", 6},
  {"No LPD lockfile specified!", 7},
  {"\
Another print spooler is using TCP printer port, possibly lpd process '%d'", 8},
  {"Another print spooler is using TCP printer port", 9},
  {"lpd: main() dofork failed", 10},
  {"lpd: pipe call failed", 11},
  {"lpd: select error!", 12},
  {"lpd: accept on listening socket failed", 13},
  {"Setuplog: dup of %d failed", 14},
  {"Setuplog: open /dev/null failed", 15},
  {"Setuplog: dup2 failed", 16},
  {"Setuplog: dup2 of %d failed", 17},
  {"Service_connection: dofork failed", 18},
  {"Service_connection: cannot read request", 19},
  {"Service_connection: bad request line '%s'", 20},
  {"Service_connection: bad protocol family '%d'", 21},
  {"no connect permissions\n", 22},
  {"Service_connection: bad request line '\\%d'%s'", 23},
  {"lpd: dofork failed", 24},
  {"lpd: Cannot open '%s'", 25},
  {"bad control command '%s'", 26},
  {"printer '%s' has illegal char '%c' in name", 27},
  {"%s: unknown control request '%s'", 28},
  {"%s: no permission to get status", 29},
  {"%s: no permission to control queue", 30},
  {"Use: MOVE printer (user|jobid)* target", 31},
  {"Job_control: error '%s'", 32},
  {"%-18s WARNING %s\n", 33},
  {" printer %s@%s not in printcap", 34},
  {" no spooling, forwarding directly to %s@%s", 35},
  {"%s: destination printer too long '%s'", 36},
  {"not implemented yet", 37},
  {"killing server PID %d\n", 38},
  {"Do_queue_control: write to pipe '%d' failed", 39},
  {"enabled and started", 40},
  {"disabled and stopped", 41},
  {"stopped", 42},
  {"started", 43},
  {"disabled", 44},
  {"enabled", 45},
  {"redirected", 46},
  {"holdall on", 47},
  {"holdall off", 48},
  {"move done", 49},
  {"class updated", 50},
  {"selected '%s'", 51},
  {"holdall", 52},
  {"autohold", 53},
  {"forward format is printer@host, not '%s'", 54},
  {"too many arguments", 55},
  {"forwarding to '%s'", 56},
  {"forwarding off", 57},
  {"classes printed '%s'", 58},
  {"all classes printed", 59},
  {"debugging override set to '%s'", 60},
  {"debugging override off", 61},
  {"Server PID %d\n", 62},
  {"Server PID %d sent SIGHUP\n", 63},
  {"Server PID %d, SIGHUP failed %s\n", 64},
  {"\
usage: %s [-FVci] [-D dbg] [-L log]\n\
 Options\n\
 -D dbg      - set debug level and flags\n\
                 Example: -D10,remote=5\n\
                 set debug level to 10, remote flag = 5\n\
 -F          - run in foreground, log to stderr\n\
               Example: -D10,remote=5\n\
 -L logfile  - append log information to logfile\n\
 -P printer  - start up single printer (test mode)\n\
 -i          - specify if started by INETD\n\
 -V          - show version info\n", 65},
  {"%s: bad printer name", 66},
  {"%s: spooling disabled", 67},
  {"%s: Receive_job: sending ACK 0 failed", 68},
  {"%s: bad file name format '%s'", 69},
  {"%s: bad file type 0x%x, not data or control", 70},
  {"%s: bad file length format '%s'", 71},
  {"%s: missing job file name", 72},
  {"%s: file '%s' name format not [cd]f[A-Za-z]NNNhost", 73},
  {"%s: additional control file being received! '%s'", 74},
  {"%s: cannot unlink '%s' ", 75},
  {"%s: cannot lock '%s' ", 76},
  {"truncate of '%s' failed - %s", 77},
  {"%s: job size too large '%s'", 78},
  {"%s: insuffcient file space '%s'", 79},
  {"%s: sending ACK 0 for '%s' failed", 80},
  {"%s: zero length job file '%s'", 81},
  {"%s: transfer of '%s' from '%s' failed", 82},
  {"%s: fstat '%s' failed '%s'", 83},
  {"%s: lseek '%s' failed '%s'", 84},
  {"Receive_job: authorization in non-authorized transfer", 85},
  {"Receive_job: missing authorization information", 86},
  {"line '%s' %d tokens", 87},
  {"Scan_block_file: lseek failed '%s'", 88},
  {"bad length information '%s'", 89},
  {"bad name information '%s'", 90},
  {"Scan_block_file: error reading file '%s'", 91},
  {"Scan_block_file: authorization in non-authorized transfer", 92},
  {"cannot lock '%s' ", 93},
  {"write of '%s' failed - %s", 94},
  {"Scan_block_file: read of '%s' failed - %s", 95},
  {"read_one_line: error reading '%s' - '%s'", 96},
  {"%s: queue full - no space", 97},
  {"missing control file", 98},
  {"no data files transferred", 99},
  {"no data files in job", 100},
  {"missing data files in job", 101},
  {"authentication information in non-authenticated job", 102},
  {"missing authentication information in forwarded job", 103},
  {"cannot do routing for %s", 104},
  {"cannot rename '%s' to '%s' - %s", 105},
  {"could not write hold file", 106},
  {"%s: rejecting forwarded job originally from '%s'", 107},
  {"%s: no permission to accept job", 108},
  {"Start_all: fork failed!", 109},
  {"Do_queue_jobs: %s", 110},
  {"Do_queue_jobs: cannot open '%s'", 111},
  {"Do_queue_jobs: Mergesort failed", 112},
  {"cannot update hold file for '%s'", 113},
  {"Do_queue_jobs: cannot update hold file for '%s'", 114},
  {"copying job '%s' to '%s'", 115},
  {"error copying job to %s", 116},
  {"Do_queue_jobs: routing loop for '%s', dest '%s'", 117},
  {"Do_queue_jobs: fork failed", 118},
  {"treating as successful", 119},
  {"retrying job", 120},
  {"aborting server", 121},
  {"removing job", 122},
  {"holding job", 123},
  {"unexpected status 0x%x", 124},
  {"aborting operations on destination '%s'", 125},
  {"aborting operations on job %s", 126},
  {"removing job due to failures", 127},
  {"Fork_subserver: fork failed", 128},
  {"Wait_for_subservers: waitpid error", 129},
  {"Wait_for_subservers: Mergesort failed", 130},
  {"link_or_copy: cannot unlink '%s'", 131},
  {"link_or_copy: cannot open for reading '%s'", 132},
  {"link_or_copy: cannot lock for writing '%s'", 133},
  {"link_or_copy: cannot truncate '%s'", 134},
  {"link_or_copy: write failed to '%s'", 135},
  {"link_or_copy: read failed '%s'", 136},
  {"Copy_job: cannot stat '%s'", 137},
  {"Decode_transfer: pipe failed", 138},
  {"flag %d", 139},
  {"error '%s'", 140},
  {"hold_info.active %d", 141},
  {"hold_info.hold_time %d", 142},
  {"hold_info.remove_time %d", 143},
  {"hold_info.done_time %d", 144},
  {"hold_info.held_class %d", 145},
  {"dest error '%s'", 146},
  {"dest active '%d'", 147},
  {"no permission to print job %s", 148},
  {"Sendmail: fdopen failed", 149},
  {"From: %s@%s\n", 150},
  {"\
Subject: %s@%s job %s\n\
\n", 151},
  {"printer %s job %s", 152},
  {" was successful.\n", 153},
  {" failed, and retry count was exceeded.\n", 154},
  {" failed and could not be retried.\n", 155},
  {" died a horrible death.\n", 156},
  {"   Status: %s", 157},
  {"missing printer name", 158},
  {"%s: no permission to show status", 159},
  {"Job_status: error '%s'", 160},
  {"%s: no permission to list jobs", 161},
  {"(originally %s) ", 162},
  {"\
\n\
 Error: ", 163},
  {"\
\n\
 Forwarding_only: %s@%s", 164},
  {" (forwarding to %s@%s)", 165},
  {"(dest %s@%s)", 166},
  {"\
\n\
 Comment: %s", 167},
  {"\
\n\
 Printing: %s\n\
 Spooling: %s", 168},
  {"\
\n\
 Bounce_queue: %s", 169},
  {"\
\n\
 Routing_filter: %s", 170},
  {" (%sbounce to %s)", 171},
  {"%s is already a subserver!", 172},
  {"\
\n\
 Subservers: ", 173},
  {" (subservers", 174},
  {"\
\n\
 Serving: %s", 175},
  {" (serving %s)", 176},
  {" %d job%s\n", 177},
  {" Queue: no printable jobs in queue\n", 178},
  {" Queue: %d printable job%s\n", 179},
  {"  Holding: %d held jobs in queue\n", 180},
  {" Server: no server active", 181},
  {" Server: pid %d active", 182},
  {" Unspooler: pid %d active", 183},
  {" Classes: %s\n", 184},
  {" Filter_status", 185},
  {"redirect->%s", 186},
  {" Job: %s", 187},
  {"%s status= %s\n", 188},
  {"%s size= %d\n", 189},
  {"%s time= %s\n", 190},
  {"%s error= %s\n", 191},
  {"%s CONTROL=\n", 192},
  {"%s HOLDFILE=\n", 193},
  {"<cpy %d/%d> ", 194},
  {"rterror", 195},
  {"ERROR: %s", 196},
  {"actv", 197},
  {"hold", 198},
  {"done", 199},
  {"printer '%s' cannot be remote and subserver", 200},
  {"Get_queue_status: error '%s'", 201},
  {" ERROR: ", 202},
  {"setstatus: cannot seek '%s'", 203},
  {"missing user name", 204},
  {"%s: no permission to remove jobs", 205},
  {"Job_remove: error '%s'", 206},
  {"token[%d] '%s'", 207},
  {"??? odd error???", 208},
  {"Printer %s@%s: \n", 209},
  {"%s: no permission to remove files", 210},
  {"checking '%s'\n", 211},
  {"  checking perms '%s'\n", 212},
  {"  no permissions '%s'\n", 213},
  {"  not selecting '%s'\n", 214},
  {"  dequeued '%s' destination %s\n", 215},
  {"  dequeued '%s'\n", 216},
  {"entry deleted", 217},
  {"error: could not remove '%s'", 218},
  {"killing subserver '%d'\n", 219},
  {"Get_queue_remove: bounce queue '%s' missing host", 220},
  {"Get_queue_remove: routing loop for '%s'", 221},
  {"bad command line '%s'", 222},
  {"bad command '%s'", 223},
  {"secure command not supported", 224},
  {"%s: Receive_secure: sending ACK 0 failed", 225},
  {"Receive_secure: cannot create temp file", 226},
  {"Send_files: pipe failed", 227},
  {"Receive_secure: transfer process failed", 228},
  {"Receive_secure: dup of %d to %d failed - %s", 229},
  {"Receive_secure: reopen of '%s' failed - %s", 230},
  {"Receive_secure: lseek of temp_fd failed - %s", 231},
  {"Receive_secure: authenication missing in forwarded job", 232},
  {"Receive_secure: command file too large", 233},
  {"Receive_secure: read of temp_fd failed - %s", 234},
  {"Receive_secure: wrong number of lines in file", 235},
  {"Receive_secure: missing forwarded authentication", 236},
  {"Receive_secure: forward information and not from server", 237},
  {"Receive_secure: bad request line '%s'", 238},
  {"Receive_secure: no permission to start printer %s", 239},
  {"scheduler is running\n", 240},
  {"system default destination: %s\n", 241},
  {"Printer: %s is %s@%s\n", 242},
  {"LOGNAME and USER environment variable not set", 243},
  {"\
usage: %s [-aAclV] [-Ddebuglevel] [-Pprinter] [-tsleeptime]\n\
  -a           - all printers\n\
  -A           - use authentication\n\
  -c           - clear screen before update\n\
  -l           - increase (lengthen) detailed status information\n\
                 additional l flags add more detail.\n\
  -Ddebuglevel - debug level\n\
  -Pprinter    - specify printer\n\
  -s           - short (summary) format\n\
  -tsleeptime  - sleeptime between updates\n\
  -V           - print version information\n", 244},
  {"\
usage: %s [-d] [-r] [-R] [-s] [-t] [-a [list]]\n\
  [-c [list]] [-f [list] [-l]] [-o [list]]\n\
  [-p [list]] [-P] [-S [list]] [list]\n\
  [-u [login-ID-list]] [-v [list]]\n\
 list is a list of print queues\n\
 -a [list] destination status *\n\
 -c [list] class status *\n\
 -f [list] forms status *\n\
 -o [list] job or printer status *\n\
 -p [list] printer status *\n\
 -P        paper types - ignored\n\
 -r        scheduler status\n\
 -s        summary status information - short format\n\
 -S [list] character set - ignored\n\
 -t        all status information - long format\n\
 -u [joblist] job status information\n\
 -v [list] printer mapping *\n\
  * - long status format produced\n", 245},
  {"nothing to print", 246},
  {"Error unlinking '%s' - %s", 247},
  {"You have already specified STDIN in the job list", 248},
  {"Make_temp_fd failed", 249},
  {"You have closed STDIN! cannot pipe from a closed connection", 250},
  {"Copy_stdin: write to temp file failed", 251},
  {"Copy_stdin: fstat '%s' failed", 252},
  {"Cannot open file '%s', %s", 253},
  {"Check_files: you did not allocate enough space for files", 254},
  {"cannot print '%s': %s", 255},
  {"not a regular file", 256},
  {"cannot read it", 257},
  {"executable program", 258},
  {"archive file", 259},
  {"unprintable file", 260},
  {"USER environment variable undefined", 261},
  {"-ncopies -number of copies must be greater than 0\n", 262},
  {"bad -F format string '%s'\n", 263},
  {"duplicate format specification -F%s\n", 264},
  {"-Kcopies -number of copies must be greater than 0\n", 265},
  {"missing printer name in -P option\n", 266},
  {"duplicate option %c", 267},
  {"Missing mail name", 268},
  {"duplicate format specification -%c\n", 269},
  {"LPRng Version %s Copyright 1988-1997\n", 270},
  {"  Patrick Powell, San Diego, <papowell@sdsu.edu>\n", 271},
  {"  Use -VV to see Copyright details\n", 272},
  {"\
usage summary: %s [ -Pprinter[@host] ] [-(K|#)copies] [-Cclass][-Jinfo]\n\
   [-Raccountname] [-m mailaddr] [-Ttitle] [-i indent]\n\
   [-wnum ][ -Zoptions ] [ -Uuser ] [ -Fformat ] [ -bhkr ]\n\
   [-Ddebugopt ] [ filenames ...  ]\n\
 -b,l        - binary or literal format\n\
 -Cclass  - job class\n\
 -F format   - job format filter\n\
   -c,d,f,g,l,m,p,t,v are also format specifications\n\
 -h          - no header or banner page\n\
 -i indent   - indentation\n\
 -Jinfo   - banner and job information\n\
 -k          - non seKure filter operation, create temp file for input\n\
 -K copies, -# copies   - number of copies\n\
 -m mailaddr - mail error status to mailaddr\n\
 -Pprinter[@host] - printer on host (default environment variable PRINTER)\n\
 -r          - remove named files after spooling\n\
 -w width    - width to use\n\
 -Q          - put 'queuename' in control file\n\
 -Raccntname - accounting information\n\
 -T title    - title for 'pr' (-p) formatting\n\
 -U username - override user name (restricted)\n\
 -V          - Verbose information during spooling\n\
 -Z filteroptions - options to pass to filter\n\
   default job format -Ff\n\
 A filename of the form '-' will read from stdin.\n\
 PRINTER environment variable is default printer.\n", 273},
  {"\
usage summary: %s [ -c ] [ -m ] [ -p ] [ -s ] [ -w ] [ -d dest ]\n\
  [ -f form-name [ -d any ] ] [ -H special-handling ]\n\
  [ -n number ] [ -o option ] [ -P page-list ]\n\
  [ -q priority-level ] [ -S character-set [ -d any ] ]\n\
  [ -S print-wheel [ -d any ] ] [ -t title ]\n\
  [ -T content-type [ -r ] ] [ -y mode-list ]\n\
  [ file...  ]\n\
 lp simulator using LPRng,  functionality may differ slightly\n\
 -A          - use authenticated transfer\n\
 -c          - (make copy before printing - ignored)\n\
 -d printer  - destination printer\n\
 -D debugflags  - debugging flags\n\
 -f formname - first letter used as job format\n\
 -H handling - (passed as -Z handling)\n\
 -m          - mail sent to $USER on completion\n\
 -n copies   - number of copies\n\
 -o option     nobanner, width recognized\n\
               (others passed as -Z option)\n\
 -P pagelist - (print page list - ignored)\n\
 -p          - (notification on completion - ignored)\n\
 -q          - priority - 0 -> Z (highest), 25 -> A (lowest)\n\
 -s          - (suppress messages - ignored)\n\
 -S charset  - (passed as -Z charset)\n\
 -t title    - job title\n\
 -T content  - (passed as -Z content)\n\
 -w          - (write message on completion - ignored)\n\
 -y mode     - (passed as -Z mode)\n\
 A filename of the form '-' will read from stdin.\n\
 LPDEST, then PRINTER environment variables are default printer.\n", 274},
  {"No server host specified", 275},
  {"Priority (first letter of Classname) not 'A' (lowest) to 'Z' (highest)", 276},
  {"-U (username) can only be used by ROOT", 277},
  {"Cannot specify binary with format '%s'", 278},
  {"Bad format specification '%s'", 279},
  {"Sorry, can only print 52 files at a time, split job up", 280},
  {"\
usage: %s [-A] [-Ddebuglevel] (jobid|user|'all')* [printer]\n\
  -A           - use authentication\n\
  -Ddebuglevel - debug level\n\
  user           removes user jobs\n\
  all            removes all jobs\n\
  jobid          removes job number jobid\n\
 Example:\n\
    'clean 30 lp' removes job 30 on printer lp\n\
    'clean'       removes first job on default printer\n\
    'clean all'      removes all your jobs on default printer\n\
    'clean all all'  removes all your jobs on all printers\n\
  Note: lprm removes only jobs for which you have removal permission\n", 281},
  {"\
usage: %s [-A] [-a | -Pprinter] [-Ddebuglevel] (jobid|user|'all')*\n\
  -a           - all printers\n\
  -A           - use authentication\n\
  -Pprinter    - printer (default PRINTER environment variable)\n\
  -Ddebuglevel - debug level\n\
  -V           - show version information\n\
  user           removes user jobs\n\
  all            removes all jobs\n\
  jobid          removes job number jobid\n\
 Example:\n\
    'lprm -Plp 30' removes job 30 on printer lp\n\
    'lprm -a'      removes all your jobs on all printers\n\
    'lprm -a all'  removes all jobs on all printers\n\
  Note: lprm removes only jobs for which you have removal permission\n", 282},
};

int _msg_tbl_length = 282;
