#!/bin/sh
for i ; do
	name=`basename $i .c`
	echo $i ${name}.h;
	inc=${name}.h;
	if grep -s $inc $i; then
		echo OK $i;
	else
		echo NEEDS $i;
		if [ -f include/$inc ]; then
			echo INCLUDE $i;
		fi;
	fi;
done;
