#!/bin/sh
# findchange olddir
# find all the files that have changed
#
if test "$#" -eq 0 ; then
	echo error - missing directory name
	echo use: $0 olddir
	exit 1;
fi;

find . -type f ! -name '*,v' -print >/tmp/file$$
for i in ` cat /tmp/file$$ `;
do
	echo $i $1/$i
	if test -f $1/$i; then
		diff -c $i $1/$i;
	else
		echo NEWFILE $i
	fi;
done
