#!/bin/sh
sed -n -e 's/:.*`/ /' -e "/struct p/d" -e /gmake/d -e /gcc/d -e "s/'.*//p" $* \
	| while read file var; do
	if [ "$var" == "struct printcap_entry" ] ; then
		inc=printcap.h;
	else
		inc=`grep -l $var include/*` ;
	fi;
	if [ -n "$inc" ]; then
		inc=`basename "$inc"`;
		echo $inc $file
	fi;
done | sort | uniq 
#
#
#
#while read inc filename; do
#	echo $filename;
#	awk "
#/ENDINCLUDE/{
#	print \"#include \\\"$inc\\\"\";
#	print \$0;
#	next;
#}
#{
#	print \$0;
#} " $filename >/tmp/d ;
#cp $filename $filename.bak
#rm $filename;
#cp /tmp/d $filename;
#done;
