#!/bin/sh
name=$1
NAME=`echo $name |tr 'a-z' 'A-Z'`
sed -e s/merge/$name/ -e s/MERGE/$NAME/ /tmp/t >/tmp/$$
echo  >>/tmp/$$
cat $2 >>/tmp/$$
echo  >>/tmp/$$
echo '#endif'  >>/tmp/$$
mv /tmp/$$ include/${name}.h
