#!/bin/sh
PATH_PREFIX=/usr
LPD_PATH="/usr/sbin/lpd"
INSTALL="/usr/bin/install -c -o root -g wheel"
LPD_PERMS_PATH="/etc/lpd.perms"
LPD_CONF_PATH="/etc/lpd.conf"
PRINTCAP_PATH="/etc/printcap"
SYSCONFDIR=/etc
SBINDIR=/usr/sbin
FILTER_DIR=/usr/libexec/filters
LOCKFILE="/var/run/lpd"
PSHOWALL="-ax"
VERSION=3.7.8
INIT=
#
# -- START --
# preremove.freebsd.sh,v 1.1 2001/08/21 20:33:17 root Exp
#
# This is the shell script that does the preremove
# lpd shutdown.  It is the script from hell
echo RUNNING preremove.freebsd.sh parms "'$0 $@'"
if [ "X$2" = "XDEINSTALL" ] ; then
	echo "Stopping LPD"
	kill -INT `ps ${PSHOWALL} | awk '/lpd/{ print $1;}'` >/dev/null 2>&1
fi
exit 0
