#!/usr/local/bin/perl
$length = 30;
while( defined( $line = <> ) ){
	#print $line;
	$line =~ m/name="([^"]*)"/;
	$name = $1;
	$name =~ s/\s*$//;
	$name =~ s/^\s*//;
	$name =~ s/.lowbar./ /g;
	$pad = '<tt>' . '&nbsp;' x ($length - length($name)) . '</tt>';
	#print "X${name}X\n";
	$line =~ s,</tt>,</tt>$pad,;
	print $line;
}
