#!/usr/local/bin/perl
my($line,$count,@lines,@width);
@width = (20,20,0);
$count = 0;
while( defined( $line = <> ) ){
	chomp $line;
	if( $line eq "\@" ){
		print join( "\n", @lines ) . " <newline>\n";
		$count = 0;
		@lines = ();
		next;
	}
	if( $line eq "|" ){
		next;
	}
	if( defined $width[$count] ){
		$line = '<tt>' . $line . '&nbsp;' x ($width[$count] - length($line)) . '</tt>';
	}
	$lines[$count++] = $line;
}
